### ISSUE TITLE
Trying to find  the index of the neighbors of each cell 

### ISSUE THREAD

**Issue by joe-protz** [joe-protz/JSLife#1]
Im trying to find the neighbors of each cell so that each cell can know how many neighbors are alive/dead. 

I've created an array of cells, represented on canvas as shown below 
## Class Cell
``` js

'use strict'

class Cell {
  constructor(x, y, scale) {
    this.alive = false
    this.scale = scale
    this.x = x
    this.y = y
  }
  // have count of alive neighbors that must be equal to 2 or 3 to stay alive or if 3 live neighbors will come alive
  getNeighbors() {
    // The formula to find a vector and a one dimensional array is X plus Y times columns 

    // THIS IS NOT RIGHT
    this.neighbors = [
      cells[(((this.x - scale) + (this.y - scale)) * (width / scale))],

      cells[((this.x + (this.y - scale)) * (width / scale))],

      cells[(((this.x + scale) + (this.y - scale)) * (width / scale))],

      cells[(((this.x - scale) + this.y) * (width / scale))],

      cells[(((this.x + scale) + this.y) * (width / scale))],

      cells[(((this.x - scale) + (this.y + scale)) * (width / scale))],

      cells[((this.x + (this.y + scale)) * (width / scale))],
      cells[(((this.x + scale) + (this.y + scale)) * (width / scale))],


    ]
    console.log(this.neighbors)
  }
  // just changes alive state
  click() {
    this.alive = true
  }
  // shows a rectangle (square) at the location and red if dead, green if alive
  show() {
    if (this.alive) {
      fill(0, 255, 0)
    } else {
      fill(255, 0, 0)
    }
    rect(this.x, this.y, scale, scale)
  }
}
```

## Setup and draw, where setup is run first to create a canvas, and draw creates things on the canvas in a loop. 

```js
// holds all cells for the board
let cells = []
// scale to make the cells larger/smaller
let scale = 100
// have I clicked start?
let start = false

function setup() {

  frameRate(10)
  createCanvas(300, 300);

  button = createButton('start');
  button.position(30, height + 30);
  // starts the game
  button.mousePressed(() => start = true)
  // creates new cells for the board and pushes them into cells in order
  for (i = 0; i < (width / scale); i++) {
    for (j = 0; j < (height / scale); j++) {
      cells.push(new Cell(j * scale, i * scale, scale))

    }
  }
}
// continuously loops @ framerate
function draw() {

  background(62)
  // loop for setting game up
  if (!start) {

    cells.forEach((cell, index) => {
      // when a pressed mouse is over a cell, change it to alive
      if (mouseIsPressed) {
        if (dist(mouseX - scale / 2, mouseY - scale / 2, cells[index].x, cells[index].y) < scale / 2) {
          cells[index].click()
        }
      }
      //show all cells 
      cells[index].show()

    })
  }
  // loop for once the game is setup and button has been pressed
  if (start) {
    cells.forEach((cell, index) => {
      cells[index].show()
      // getNeighbors is needed to use the rules. doesn't yet work.
      cells[index].getNeighbors()
    })
    noLoop() // this stops the draw loop, just there for debugging
  }

}
```

## Issue

Im trying to find the neighbors of each cell. I'm sure there is some formula to do so, but I'm struggling to figure it out. I've whiteboarded it out but can't seem to find a solid connection between x,y and index #. I've scaled it down to 9 cells for the purpose of  brainstorming. 

I'd like my Obj.neighbors function to create an attribute for the cell instance where it has an array of all of its neighbors to reference. I have seen formulas to convert x,y into an index before and I thought I was on the right track but the neighbors it currently finds is way off.

**Comment by joe-protz** [comment]
In this particular setup, here are the indexes and (x,y) of each cell.
![Screen Shot 2020-02-06 at 2 08 26 PM](https://user-images.githubusercontent.com/58189799/73969930-45463e80-48ea-11ea-9512-fa3892709faf.png)

**Comment by MicFin** [comment]
A cell can have up to 8 neighbors.  As long as you know the cells row (x) and column (y) then you should be able to find the neighbors.

current row (x) = 1
current column (y) = 1

[ ][  ][ ][ ]
[ ][a][ ][ ]
[ ][  ][ ][ ]

## Check for the easy neighbors first.  

[ ][  ][ ][ ]
[ ][a][*][ ]
[ ][  ][ ][ ]

#### To the right
- y is the same, x is + 1
- so position is 2, 1

[ ][  ][ ][ ]
[*][a][][ ]
[ ][  ][ ][ ]

#### To the left
- y is the same, x is - 1
- so position is 0, 1

[ ][*][ ][ ]
[ ][a][ ][ ]
[ ][  ][ ][ ]

#### To the top
- x is the same, y is - 1
- so position is 1, 0

[ ][ ][ ][ ]
[ ][a][ ][ ]
[ ][*][ ][ ]

#### To the bottom
- x is the same, y is + 1
- so position is 1, 2

First work on a function that can find if a cell has those neighbors and what the values of its neighbors are.  Dont worry about the diagonals at first.

After you solve for that, you can think about the diagonals and 

### Neighbors List

array[x][y] has neighbors

array[x-1][y] left
array[x][y-1] top
array[x+1][y] right
array[x][y+1] bottom
array[x-1][y-1] top left
array[x+1][y-1] top right
array[x+1][y+1] bottom right
array[x-1][y+1] bottom left

**Comment by joe-protz** [comment]
That's kind of where I got tripped up.

A few issues,

# 1
The cells aren't stored in a 2d array, but a normal flat array. I push them in my nested loop in order such as that cells[0] = {x=0, y=0} , cells[3] = {x=0, y=100} and then the rectangles are drawn on canvas based on the X and Y(where x,y === the top corner of the rectangle)

Because of this I can't lookup by x,y coordinate , or it'd be a lot easier but I was struggling to create the 2d array as needed. doing cells[i][j]= new Cell was throwing an error because j was not defined for i. I instead am pushing new cells into the array in order.

# 2 
The scale is tripping me up a little I think. I'm not dealing with x-1 , it'd be x-100. Although now that I type it out, it seems that the x and y simply need to be divided by scale, as that's what they were originally multiplied by.

**Comment by MicFin** [comment]
You can turn your 1d array into a 2d array when trying to find the neighbors.  But dont have to use a 2d array.
https://stackoverflow.com/questions/22464605/convert-a-1d-array-to-2d-array

Dont let the scale or size of the grid get to you.  First solve it for a smaller grid like you were thinking about doing 4x4 or 5x5 should be fine.  Here's a good visual of how to think about the neighbors when using a 2d array.  It can be easier to see the formula when you visualize it like this.

https://github.com/phugh/grid-neighbors-1d

Again, always start with the simpler neighbors.  The neighbors directly to the left and right should be where you start.

**Comment by joe-protz** [comment]
I wrote 8 formulas based on eliminating the scale aspect and using the formula index = x+(y*columns) 

```js
 this.neighbors = [
      cells[(this.x - scale) / scale + (this.y - scale) / scale * (width / scale)],

      cells[this.x / scale + (this.y - scale) / scale * (width / scale)],

      cells[(this.x + scale) / scale + (this.y - scale) / scale * (width / scale)],

      cells[(this.x - scale) / scale + this.y / scale * (width / scale)],

      cells[(this.x + scale) / scale + this.y / scale * (width / scale)],
//  #6
      cells[(this.x - scale) / scale + (this.y + scale) / scale * (width / scale)],

      cells[this.x / scale + (this.y + scale) / scale * (width / scale)],

      cells[(this.x + scale) / scale + (this.y + scale) / scale * (width / scale)],


    ]
```

However # 6 seems to be faulty. See attached image
![Screen Shot 2020-02-06 at 3 36 55 PM](https://user-images.githubusercontent.com/58189799/73976553-8c3a3100-48f6-11ea-9379-a32fe4d28a8f.png)


I am checking the attributes  of cell[0], so top left.
It is saying that the 6th neighbor is alive and is the single green square, which is obviously not a neighbor. But I keep looking at the formula, and it seems right. The order I wrote them is assuming the current cell is center,

0: top left
1: top center
2:top right
3: left
4:right 
5: bottom left
6: bottom center
7: bottom right

**Comment by joe-protz** [comment]
![IMG_0090](https://user-images.githubusercontent.com/58189799/73977241-00290900-48f8-11ea-9731-bb89782a6225.JPG)


I should be getting -3 which is undefined?

**Comment by joe-protz** [comment]
## OKAY SO

1) I see now I needed parens around my y/scale section of the formula.

Now my formula is working as intended. It does get any EXISTING neighbor, however I ran into a problem . 

#2 in the index, because of the way we check the formula, is actually evaluating to index 0 as a neighbor. 

(200+100)/100 + ((0-100)/100) * 3 

3+-3
0

I am sure there are other instances of similar problems. So it seems this formula doesn't work if we are trying to find neighbors that are off of the array. 

I need a way to stop it from checking neighbors out of bounds, I guess. It's starting to seem easier to map to a 2d array, because if I try to check a 2d array for something that doesn't exist, it wont EVER return a value, it'll be undefined.

**Comment by joe-protz** [comment]
solved by covering edge cases 

```js
  getNeighbors() {
    // The formula to find a vector and a one dimensional array is X plus Y times columns 


  


    if (this.touchesTop || this.touchesLeft) {
      this.neighbors[0] = undefined
    } else {
      this.neighbors[0] = cells[(this.x - scale) / scale + ((this.y - scale) / scale) * (width / scale)]
    }

    if (this.touchesTop) {
      this.neighbors[1] = undefined
    } else {
      this.neighbors[1] = cells[this.x / scale + ((this.y - scale) / scale) * (width / scale)]
    }

    if (this.touchesTop || this.touchesRight) {
      this.neighbors[2] = undefined
    } else {
    this.neighbors[2] = cells[((this.x + scale) / scale) + ((this.y - scale) / scale) * (width / scale)]
    }

     if (this.touchesLeft) {
       this.neighbors[3] = undefined
     } else {
      this.neighbors[3] = cells[(this.x - scale) / scale + (this.y / scale) * (width / scale)]
     }

     if (this.touchesRight) {
       this.neighbors[4] = undefined
     } else {
     this.neighbors[4]  = cells[(this.x + scale) / scale + (this.y / scale) * (width / scale)]
     }

     if (this.touchesBottom || this.touchesLeft) {
       this.neighbors[5] = undefined
     } else {
      this.neighbors[5] = cells[(this.x - scale) / scale + ((this.y + scale) / scale) * (width / scale)]
     }

     if(this.touchesBottom) {
       this.neighbors[6]  = undefined
     } else {
      this.neighbors[6] = cells[this.x / scale + ((this.y + scale) / scale) * (width / scale)]
     }

     if (this.touchesBottom || this.touchesRight) {
       this.neighbors[7] = undefined
     } else{
     this.neighbors[7] = cells[(this.x + scale) / scale + ((this.y + scale) / scale) * (width / scale)]
     }
  }

```
